# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeM_kKeyI80MwB2atoml35M_dQLlscfg
"""

# Foydalanuvchidan ism va yoshini so'rash
ism = input("Ismingizni kiriting: ")
yosh = int(input("Yoshingizni kiriting: "))

# Natijani chiqarish
print(f"Xush kelibsiz, {ism}! Sizning yoshingiz {yosh} da.")